name: ec2_deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Create Private Key File & SSH Config
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deployment.key
        chmod 600 ~/.ssh/deployment.key
        cat >>~/.ssh/config <<END
        Host deployment
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deployment.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_DEPLOY_USER }}
        SSH_HOST: ${{ secrets.SSH_DEPLOY_HOST }}

    - name: Copy index.html to Server
      run: | 
        scp -i ~/.ssh/deployment.key ./index.html $SSH_USER@$SSH_HOST:/home/ec2-user/www
      env:
        SSH_USER: ${{ secrets.SSH_DEPLOY_USER }}
        SSH_HOST: ${{ secrets.SSH_DEPLOY_HOST }}
