name: ec2_deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Create Private Key File & SSH Config
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deployment.pem
        chmod 600 ~/.ssh/deployment.pem
      env:
        SSH_KEY: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}

    - name: Copy index.html to Server
      run: | 
        scp -i ~/.ssh/deployment.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null index.html $SSH_USER@$SSH_HOST:/home/ec2-user/www
      env:
        SSH_USER: ${{ secrets.SSH_DEPLOY_USER }}
        SSH_HOST: ${{ secrets.SSH_DEPLOY_HOST }}
